;; Auto-generated by consult-templates.el -*- lexical-binding: t -*-
(setq consult-templates '(("provide call" . "(provide '") ("autoload" . ";;;###autoload")
                          ("lexical binding" . ";;; -*- lexical-binding: t -*-"))
)
