;; Auto-generated by consult-templates.el -*- lexical-binding: t -*-
(setq consult-templates '(("provide call" . "(provide '") ("autoload" . ";;;###autoload")
                          ("lexical binding" . ";;; -*- lexical-binding: t -*-")
                          ("Collection: Places" . "[[denote:20260508T183256][Places]]")
                          ("Collections: People" . " [[denote:20260622T191924][People]]")
                          ("Collections: Moments" . " [[denote:20260604T210810][Moments]]")
                          ("Collections: Love" . " [[denote:20260601T183750][Love]]")
                          ("Collections: Life" . " [[denote:20260613T143309][Life]]"))
)
